#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Shopware\CI\Command\CreateReleaseBranchCommand;
use Shopware\CI\Command\DeleteTagCommand;
use Shopware\CI\Command\GenerateChangelogCommand;
use Shopware\CI\Command\ShowNextTagCommand;
use Symfony\Component\Console\Application;

$application = new Application('Shopware CI');

$application->add(new GenerateChangelogCommand());
$application->add(new ShowNextTagCommand());
$application->add(new CreateReleaseBranchCommand());
$application->add(new DeleteTagCommand());

$application->run();
